///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/maintheme.aks
/// Generation time: mar oct 30 19:42:23 CET 2018
///

/// Song 'main_theme' metadata macros
#define main_theme_address  0x63DB
#define main_theme_size     643
#define main_theme_end      0x665d

/// Song 'main_theme' array declaration
extern void main_theme[main_theme_size];
