///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/shoot.aks
/// Generation time: mar oct 30 19:42:22 CET 2018
///

/// Song 'shootSFX' metadata macros
#define shootSFX_address  0x6F48
#define shootSFX_size     101
#define shootSFX_end      0x6fac

/// Song 'shootSFX' array declaration
extern void shootSFX[shootSFX_size];
