///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: music/true_theme.aks
/// Generation time: mar oct 30 19:42:23 CET 2018
///

/// Song 'true_theme' metadata macros
#define true_theme_address  0x6A1F
#define true_theme_size     528
#define true_theme_end      0x6c2e

/// Song 'true_theme' array declaration
extern void true_theme[true_theme_size];
