// File generated by CONVERT_PALETTE macro from CPCtelera
// Converted firmware palette declaration
// 
#ifndef _tile_palette_H_
#define _tile_palette_H_

#include <types.h>

extern const u8 tile_palette[16];

#endif
